export enum ACTION {
  PROVISION_STATUS = 'PROVISION_STATUS',

  PROVISION_SUCCESS = 'PROVISION_SUCCESS',
  PROVISION_WARNING = 'PROVISION_WARNING',
  PROVISION_ERROR = 'PROVISION_ERROR',

  NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS',
  NOTIFICATION_WARNING = 'NOTIFICATION_WARNING',
  NOTIFICATION_ERROR = 'NOTIFICATION_ERROR',

  CONTEXT_MENU_CLICKED = 'CONTEXT_MENU_CLICKED'
}

export class Action {
  constructor (public type: string, public payload: any) {}
}
