export enum ACTION {
  FROM_POPUP = 'FROM_POPUP',
  NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS',
  NOTIFICATION_WARNING = 'NOTIFICATION_WARNING',
  NOTIFICATION_ERROR = 'NOTIFICATION_ERROR',
  FROM_CONTENT_SCRIPT = 'FROM_CONTENT_SCRIPT'
}

export class Action {
  constructor (public type: string, public payload: any) {}
}
